Emaildownload
HoiskolensChemikerforening/hc-backend pull request #532
Opened 2024-04-04 19:41 UTC by taraldkb

Download every committee member email as a csv file. May need to look into permissions

2024-04-08 17:01 UTC, paul673 commented on chemie/committees/templates/committees/email_download.html
> +            <th>Epost</th>
E-post

2024-04-08 17:04 UTC, paul673 commented on chemie/committees/views.py
Add permissions

2024-04-08 17:26 UTC, paul673 requested changes
Issues:
- Permissions
- Spelling "e-post"

It would be nice to have a download all csv files button as well.

2024-04-20 12:03 UTC, williadav approved these changes

2024-04-20 12:05 UTC, paul673 approved these changes

2024-08-04 17:54 UTC, merged